---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: divy
  become: false

  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "divypagariya/scientific-calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
    
    - name: Remove existing container if running
      shell: docker rm -f calculator
      ignore_errors: yes

    - name: Running container
      shell: docker run -it -d --name calculator divypagariya/scientific-calculator
