---
- name: Deploy Scientific Calculator
  hosts: localhost
  tasks:
    - name: Pull Docker image
      docker_image:
        name: divypagariya/scientific-calculator
        source: pull

    - name: Run Calculator Container
      docker_container:
        name: scientific-calculator
        image: divypagariya/scientific-calculator:latest
        state: started
        tty: yes
        stdin_open: yes
